# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wetlandlayer',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_indicator', to='swos.Indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='wetlandlayer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_product', to='swos.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wetlandlayer',
            name='wetland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_wetland', to='swos.Wetland', verbose_name='Wetland'),
        ),
    ]
