# Generated by Django 4.0.2 on 2023-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swos', '0002_auto_20200615_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wetlandlayer',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_indicator', to='swos.indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='wetlandlayer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_product', to='swos.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wetlandlayer',
            name='wetland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_wetland', to='swos.wetland', verbose_name='Wetland'),
        ),
    ]
