# Generated by Django 4.2.4 on 2023-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_climatechangescenario_climatelayer_climatemodelling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatelayer',
            name='source_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='climatelayer',
            name='tracking_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='climatelayer',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='climatelayer',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'planned'), ('internal', 'internal'), ('public', 'public'), ('external', 'external')], max_length=20, null=True),
        ),
    ]
