# Generated by Django 4.2.4 on 2024-01-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_alter_climatelayer_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatelayer',
            name='variable_name_in_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
