# Generated by Django 4.2.5 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_climatelayer_variable_name_in_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorized_filename', models.CharField(max_length=500, null=True, unique=True)),
                ('filename', models.CharField(max_length=400, null=True)),
                ('category', models.CharField(choices=[('water_budget', 'water_budget'), ('water_budget_bias', 'water_budget_bias'), ('kaariba', 'kaariba')], max_length=255, null=True)),
                ('num_bands', models.IntegerField(null=True)),
                ('timestamp_begin', models.CharField(max_length=500, null=True)),
                ('band_metadata', models.JSONField(default=dict)),
                ('net_cdf_times', models.JSONField(default=dict)),
                ('st_mtime_nc', models.CharField(max_length=255, null=True)),
                ('st_mtime_tif', models.CharField(max_length=255, null=True)),
                ('st_size_nc', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
