# Generated by Django 4.2.5 on 2024-11-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0007_tempresultfile_timestamp_begin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempresultfile",
            name="band_metadata",
        ),
        migrations.RemoveField(
            model_name="tempresultfile",
            name="net_cdf_times",
        ),
        migrations.RemoveField(
            model_name="tempresultfile",
            name="num_bands",
        ),
        migrations.RemoveField(
            model_name="tempresultfile",
            name="timestamp_begin",
        ),
    ]
