# Generated by Django 4.2.5 on 2024-11-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0008_remove_tempresultfile_band_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempresultfile",
            name="nc_meta",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
