# Generated by Django 4.2.5 on 2026-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0009_tempresultfile_nc_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolderType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("citation", models.TextField(blank=True)),
                ("header_regex", models.CharField(blank=True, max_length=255)),
                ("lineage", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("public", "Public"), ("internal", "Internal")],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("bbox_min_lon", models.FloatField()),
                ("bbox_min_lat", models.FloatField()),
                ("bbox_max_lon", models.FloatField()),
                ("bbox_max_lat", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
