# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0003_auto_20200521_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapviewer',
            name='template_file',
            field=models.FilePathField(match='.*\\.html', max_length=1000, path='C:\\Users\\c1zafr\\PycharmProjects\\GEOPORTAL_INSPIRE\\geoportal\\framework\\templates/mapviewer', verbose_name='Template file'),
        ),
    ]
