# Generated by Django 4.0.2 on 2023-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0001_initial'),
        ('mapviewer', '0004_auto_20200521_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselayerinline',
            name='baselayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapviewer.baselayer'),
        ),
        migrations.AlterField(
            model_name='baselayerinline',
            name='mapviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapviewer.mapviewer'),
        ),
        migrations.AlterField(
            model_name='layerbaseinline',
            name='mapviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapviewer.mapviewer'),
        ),
        migrations.AlterField(
            model_name='mapviewer',
            name='search_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='csw.csw', verbose_name='Server for search field'),
        ),
    ]
