# Generated by Django 4.2.5 on 2024-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0005_alter_baselayerinline_baselayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapviewer',
            name='template_file',
            field=models.FilePathField(match='.*\\.html', max_length=1000, path='C:\\Users\\da86mej\\Documents\\wis\\backend\\framework\\templates/mapviewer', verbose_name='Template file'),
        ),
    ]
