# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaenopt', '0009_auto_20180718_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='pheno',
            name='image',
            field=models.FileField(blank=True, help_text='Upload phase image', null=True, upload_to='pheno', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pheno',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phenolayer',
            name='type',
            field=models.CharField(blank=True, choices=[('insitu', 'insitu'), ('modelliert', 'modelliert'), ('differenz', 'differenz'), ('allgemein', 'allgemein'), ('geoproxy', 'geoproxy')], help_text='Untergliederung der Phenophasen-Layer', max_length=20, null=True),
        ),
    ]
