# Generated by Django 4.0.2 on 2023-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0001_initial'),
        ('phaenopt', '0010_auto_20200521_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizensciencedata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_project', to='phaenopt.citizenscienceproject', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='phenolayer',
            name='phenophase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_phenophase', to='phaenopt.pheno', verbose_name='Phenophase'),
        ),
        migrations.AlterField(
            model_name='phenolayer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_product', to='phaenopt.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='phenolayer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_region', to='geospatial.region', verbose_name='Region'),
        ),
    ]
