# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0011_auto_20211023_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformityMapInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Conformity')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('date_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='layers.ISOcodelist', verbose_name='Date type')),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintConditionsMapInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('constraints_cond', models.CharField(blank=True, max_length=400, null=True, verbose_name='Conditions applying to access and use')),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintLimitMapInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('constraints_limit', models.CharField(blank=True, max_length=400, null=True, verbose_name='Limitations on public access')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordMapInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('keyword', models.CharField(max_length=200)),
                ('uri', models.CharField(blank=True, max_length=400, null=True, verbose_name='URI')),
                ('thesaurus_name', models.CharField(blank=True, max_length=300, null=True)),
                ('thesaurus_date', models.DateField(blank=True, null=True, verbose_name='Thesaurus publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='WMS name')),
                ('service_abstract', models.CharField(blank=True, max_length=2000, null=True, verbose_name='WMS abstract')),
                ('service_publication_date', models.DateField(blank=True, null=True, verbose_name='WMS publication date')),
                ('service_identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='WMS UUID')),
                ('download_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Download nme')),
                ('download_abstract', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Download abstract')),
                ('download_publication_date', models.DateField(blank=True, null=True, verbose_name='Download publication date')),
                ('download_type', models.CharField(blank=True, default='WFS', max_length=200, null=True, verbose_name='Download type')),
                ('download_secure', models.BooleanField(default=False, verbose_name='Secure download')),
                ('download_identifier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Download UUID')),
                ('west', models.FloatField(default='9.25', help_text='e.g. -180', verbose_name='BBOX west coordinate')),
                ('east', models.FloatField(default='9.47', help_text='e.g. 180', verbose_name='BBOX east coordinate')),
                ('north', models.FloatField(default='52.16', help_text='e.g. 90', verbose_name='BBOX north coordinate')),
                ('south', models.FloatField(default='52.05', help_text='e.g. -90', verbose_name='BBOX south coordinate')),
                ('geo_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location description')),
                ('ows_url_name', models.CharField(blank=True, help_text='Used for name of Mapfile, SLD and short URL', max_length=200, null=True, verbose_name='Identifier name')),
                ('ows_title_de', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_abstract_de', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_abstract_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_style_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_rootlayer_title_de', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_rootlayer_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_rootlayer_abstract_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_rootlayer_abstract_de', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_srs', models.CharField(blank=True, default='EPSG:3857,EPSG:4258,EPSG:4326,EPSG:3034,EPSG:3035,EPSG:25832,EPSG:31467', max_length=200, null=True)),
                ('ows_languages', models.CharField(blank=True, default='ger', help_text='Add more languages separated by Comma e.g. ger, eng', max_length=200, null=True)),
                ('ows_enable_request', models.CharField(blank=True, default='*', help_text='GetCapabilities, GetMap, GetFeatureInfo and GetLegendGraphic. A ”!” in front of a request will disable the request. “*” enables all requests.', max_length=200, null=True)),
                ('distributor_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordination_contact', to='layers.Contact', verbose_name='Coordination')),
                ('metadata_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_contact', to='layers.Contact', verbose_name='Metadata contact')),
                ('ows_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wms_contact', to='layers.Contact', verbose_name='WMS contact')),
                ('service_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_contact', to='layers.Contact', verbose_name='Service contact')),
            ],
        ),
        migrations.CreateModel(
            name='MapGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ows_group_title_de', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_group_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_group_abstract_de', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_group_abstract_en', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapLayerInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ows_layer_title_de', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_layer_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_layer_abstract_de', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_layer_abstract_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('ows_layer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wms_layer_min_scale', models.IntegerField(blank=True, help_text='Lower value', null=True, verbose_name='Visibility from')),
                ('wms_layer_max_scale', models.IntegerField(blank=True, help_text='Higher value', null=True, verbose_name='Visibility to')),
                ('ows_geometry_type', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_filter_item', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_filter_value', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_layer_spatial_object_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ows_enable_request', models.CharField(blank=True, default='*', help_text='GetCapabilities, GetMap, GetFeatureInfo and GetLegendGraphic. A ”!” in front of a request will disable the request. “*” enables all requests.', max_length=200, null=True)),
                ('ows_additional_infos', models.CharField(blank=True, max_length=2000, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layer', to='map.Map')),
                ('map_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_map', to='layers.Layer')),
                ('ows_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_group', to='map.MapGroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MapLayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('template_file', models.FilePathField(blank=True, match='.*\\.xml', max_length=1000, null=True, path='C:\\Users\\c1zafr\\PycharmProjects\\GEOPORTAL_INSPIRE\\geoportal\\framework\\templates/sld', verbose_name='Template file')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineResourceMapInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('linkage', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.ISOcodelist')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_online_resource', to='map.Map')),
            ],
        ),
        migrations.AddField(
            model_name='maplayerinline',
            name='wms_layer_style_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_style', to='map.MapLayerStyle'),
        ),
        migrations.AddField(
            model_name='keywordmapinline',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_keywords', to='map.Map'),
        ),
        migrations.AddField(
            model_name='keywordmapinline',
            name='thesaurus_date_type_code_code_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_thesaurus_date_type_code_code_value', to='layers.ISOcodelist'),
        ),
        migrations.AddField(
            model_name='constraintlimitmapinline',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_constraints_limit', to='map.Map'),
        ),
        migrations.AddField(
            model_name='constraintconditionsmapinline',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_constraints_cond', to='map.Map'),
        ),
        migrations.AddField(
            model_name='conformitymapinline',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_conformity', to='map.Map'),
        ),
    ]
