# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformitymapinline',
            name='date_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='layers.ISOcodelist', verbose_name='Date type'),
        ),
        migrations.AlterField(
            model_name='keywordmapinline',
            name='thesaurus_date_type_code_code_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='map_thesaurus_date_type_code_code_value', to='layers.ISOcodelist'),
        ),
        migrations.AlterField(
            model_name='map',
            name='distributor_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_contact', to='layers.Contact', verbose_name='Coordination'),
        ),
        migrations.AlterField(
            model_name='map',
            name='metadata_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_contact', to='layers.Contact', verbose_name='Metadata contact'),
        ),
        migrations.AlterField(
            model_name='map',
            name='ows_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_contact', to='layers.Contact', verbose_name='WMS contact'),
        ),
        migrations.AlterField(
            model_name='map',
            name='service_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_contact', to='layers.Contact', verbose_name='Service contact'),
        ),
        migrations.AlterField(
            model_name='maplayerinline',
            name='map_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_map', to='layers.Layer'),
        ),
        migrations.AlterField(
            model_name='maplayerinline',
            name='ows_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='map_group', to='map.MapGroup'),
        ),
        migrations.AlterField(
            model_name='maplayerinline',
            name='wms_layer_style_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_style', to='map.MapLayerStyle'),
        ),
        migrations.AlterField(
            model_name='onlineresourcemapinline',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layers.ISOcodelist'),
        ),
    ]
