# Generated by Django 4.0.2 on 2023-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_alter_conformityinline_date_type_and_more'),
        ('map', '0002_auto_20211024_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformitymapinline',
            name='date_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'CI_DateTypeCode'}, on_delete=django.db.models.deletion.PROTECT, to='layers.isocodelist', verbose_name='Date type'),
        ),
        migrations.AlterField(
            model_name='keywordmapinline',
            name='thesaurus_date_type_code_code_value',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'CI_DateTypeCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='map_thesaurus_date_type_code_code_value', to='layers.isocodelist'),
        ),
        migrations.AlterField(
            model_name='onlineresourcemapinline',
            name='function',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'CI_OnLineFunctionCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='layers.isocodelist'),
        ),
    ]
