# Generated by Django 4.2.5 on 2024-01-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_conformitymapinline_date_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayerstyle',
            name='template_file',
            field=models.FilePathField(blank=True, match='.*\\.xml', max_length=1000, null=True, path='/opt/geoportal_tippecc/geoportal/framework/templates/sld', verbose_name='Template file'),
        ),
    ]
