# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-22 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_layer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='INSPIREthemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URI', models.CharField(max_length=400, verbose_name='URI')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (en)')),
                ('name_de', models.CharField(max_length=200, verbose_name='Name (de)')),
                ('definition_en', models.CharField(max_length=1000, verbose_name='Definition (en)')),
                ('definition_de', models.CharField(max_length=1000, verbose_name='Definition (de)      ')),
            ],
        ),
    ]
