# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_inspirethemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirethemes',
            name='topicCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicCategory', to='layers.ISOcodelist'),
        ),
        migrations.AlterField(
            model_name='inspirethemes',
            name='definition_de',
            field=models.CharField(max_length=1000, verbose_name='Definition (de)'),
        ),
    ]
