# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_auto_20200523_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='abstract_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='alternative_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
