# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20200615_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='related_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Contact', verbose_name='Related organization'),
        ),
    ]
