# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_contact_related_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='progress',
            field=models.ForeignKey(blank=True, default=184, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='layers.ISOcodelist', verbose_name='Progress'),
        ),
    ]
