# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_layer_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='denominator',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resolution'),
        ),
    ]
