# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-07 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_layer_denominator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='progress',
            field=models.ForeignKey(blank=True, default=456, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='layers.ISOcodelist', verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='scope',
            field=models.ForeignKey(default=475, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='layers.ISOcodelist'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='spat_representation_type',
            field=models.ForeignKey(blank=True, default=487, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representation_type', to='layers.ISOcodelist', verbose_name='Spatial Representation Type'),
        ),
    ]
