# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0010_auto_20201007_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspirethemes',
            name='topicCategory',
        ),
        migrations.AddField(
            model_name='keywordinline',
            name='uri',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='characterset',
            field=models.CharField(blank=True, default='utf8', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_characterset',
            field=models.CharField(blank=True, default='utf8', max_length=200, null=True, verbose_name='Metadata character set'),
        ),
        migrations.DeleteModel(
            name='INSPIREthemes',
        ),
    ]
