# Generated by Django 4.0.2 on 2023-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0004_auto_20200521_1240'),
        ('layers', '0011_auto_20211023_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformityinline',
            name='date_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'CI_DateTypeCode'}, on_delete=django.db.models.deletion.PROTECT, to='layers.isocodelist', verbose_name='Date type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='related_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='layers.contact', verbose_name='Related organization'),
        ),
        migrations.AlterField(
            model_name='keywordinline',
            name='thesaurus_date_type_code_code_value',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'CI_DateTypeCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='layers.isocodelist'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='data_source',
            field=models.ManyToManyField(blank=True, to='layers.Layer', verbose_name='Data source'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='dataset_contact_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_contact', to='layers.contact', verbose_name='Dataset contact - replaced by Dataset point  of contact(s)'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meta_contact', to='layers.contact', verbose_name='Metadata contact - replaced by metadata contacts'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='progress',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'code_list': 'MD_ProgressCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='layers.isocodelist', verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='scope',
            field=models.ForeignKey(default=1, limit_choices_to={'code_list': 'MD_ScopeCode'}, on_delete=django.db.models.deletion.PROTECT, related_name='scope', to='layers.isocodelist'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='spat_representation_type',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'code_list': 'MD_SpatialRepresentationTypeCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representation_type', to='layers.isocodelist', verbose_name='Spatial Representation Type'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='topicCategory',
            field=models.ManyToManyField(default=227, limit_choices_to={'code_list': 'MD_TopicCategoryCode'}, to='layers.ISOcodelist', verbose_name='Topic category'),
        ),
        migrations.AlterField(
            model_name='layergroupinline',
            name='mapviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapviewer.mapviewer'),
        ),
        migrations.AlterField(
            model_name='layerinline',
            name='layergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layers.layergroup'),
        ),
        migrations.AlterField(
            model_name='onlineresourceinline',
            name='function',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'CI_OnLineFunctionCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='layers.isocodelist'),
        ),
    ]
