# Generated by Django 4.0.2 on 2023-10-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_alter_conformityinline_date_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='progress',
            field=models.ForeignKey(blank=True, default=184, limit_choices_to={'code_list': 'MD_ProgressCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='layers.isocodelist', verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='scope',
            field=models.ForeignKey(default=203, limit_choices_to={'code_list': 'MD_ScopeCode'}, on_delete=django.db.models.deletion.PROTECT, related_name='scope', to='layers.isocodelist'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='spat_representation_type',
            field=models.ForeignKey(blank=True, default=215, limit_choices_to={'code_list': 'MD_SpatialRepresentationTypeCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representation_type', to='layers.isocodelist', verbose_name='Spatial Representation Type'),
        ),
    ]
