# Generated by Django 4.2.5 on 2024-09-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0013_alter_layer_progress_alter_layer_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/images/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation_ror',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation_short',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='person_orcid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='related_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.contact', verbose_name='Related organization'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='progress',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'code_list': 'MD_ProgressCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='layers.isocodelist', verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='scope',
            field=models.ForeignKey(default=1, limit_choices_to={'code_list': 'MD_ScopeCode'}, on_delete=django.db.models.deletion.PROTECT, related_name='scope', to='layers.isocodelist'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='spat_representation_type',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'code_list': 'MD_SpatialRepresentationTypeCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='representation_type', to='layers.isocodelist', verbose_name='Spatial Representation Type'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_packages',
            field=models.ManyToManyField(blank=True, to='layers.workpackage'),
        ),
    ]
