# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satdatalayer',
            name='thema',
            field=models.CharField(choices=[('Rohdaten', 'Rohdaten'), ('Produkt', 'Produkt')], default='Rohdaten', max_length=30, verbose_name='Type'),
        ),
    ]
