# Generated by Django 4.2.5 on 2024-01-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0001_initial'),
        ('content', '0004_alter_externaldatabase_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storylinepart',
            name='image',
            field=models.ImageField(blank=True, help_text='To avoid cutting off parts of your image please resize it in advance. Right position: max. 300px width; Bottom max. 600px.If you upload a GIF please make sure the size is not higher than 500kb', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='storylinepart',
            name='region',
            field=models.ForeignKey(help_text='Please click - Save and continue editing - to update the layer lists below', on_delete=django.db.models.deletion.PROTECT, to='geospatial.region'),
        ),
    ]
