name: Django CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', 3.11]
    env:
          DATABASES: 'spatialite:///test_db.sqlite3'
    steps:    
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check Formatting
      run: |
        pip install flake8
        flake8
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgdal-dev
        sudo apt-get install -y libsqlite3-mod-spatialite
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
        sudo mkdir -p /var/log/django
    - name: Run mirgate
      run: |
        python manage.py shell -c "import django;django.db.connection.cursor().execute('SELECT InitSpatialMetaData(1);')";
        python manage.py makemigrations
        python manage.py migrate
        python manage.py check
