name: trigger gitlab job

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger Job
        uses: appleboy/gitlab-ci-action@master
        with:
          url: "https://git.uni-jena.de/api/v4/projects/3567/trigger/pipeline"
          token: ${{ secrets.TOKEN }}
          project_id: 100