# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0011_auto_20211023_1604'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspireDataset',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.Layer')),
                ('opendata', models.BooleanField(default=False)),
                ('inspireidentified', models.BooleanField(default=False)),
                ('inspire_published', models.BooleanField(default=False)),
                ('inspire_first_publication_date', models.DateTimeField(blank=True, null=True, verbose_name='First publication date')),
                ('inspire_last_publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Last publication date')),
                ('processing_new_dataset', models.BooleanField(default=False, verbose_name='The content of the source dataset changes after processing')),
            ],
            bases=('layers.layer',),
        ),
        migrations.CreateModel(
            name='InspireMap',
            fields=[
                ('map_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Map')),
                ('inspire_wms_published', models.BooleanField(default=False)),
                ('inspire_wms_first_publication_date', models.DateTimeField(blank=True, null=True, verbose_name='First publication date')),
                ('inspire_wms_last_publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Last publication date')),
                ('inspire_wfs_published', models.BooleanField(default=False)),
                ('inspire_wfs_first_publication_date', models.DateTimeField(blank=True, null=True, verbose_name='First publication date')),
                ('inspire_wfs_last_publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Last publication date')),
            ],
            bases=('map.map',),
        ),
        migrations.CreateModel(
            name='InspireTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=400, verbose_name='URI')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (en)')),
                ('name_de', models.CharField(max_length=200, verbose_name='Name (de)')),
                ('definition_en', models.CharField(max_length=1000, verbose_name='Definition (en)')),
                ('definition_de', models.CharField(max_length=1000, verbose_name='Definition (de)')),
                ('topicCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topicCategory', to='layers.ISOcodelist')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name='execution date')),
                ('description', models.CharField(max_length=2000)),
                ('input_table', models.CharField(max_length=300)),
                ('output_table', models.CharField(max_length=300)),
                ('output_gml', models.FileField(blank=True, help_text='Upload output GML', null=True, upload_to='GML', verbose_name='Output GML')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_processing', to='inspire.InspireDataset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SourceLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.Layer')),
                ('internal_legal_basis', models.TextField(blank=True, max_length=1000, null=True)),
                ('internal_access_constraint', models.TextField(blank=True, max_length=300, null=True)),
                ('internal_comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('internal_pg_table_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('opendata', models.BooleanField(default=False)),
                ('inspireidentified', models.BooleanField(default=False)),
                ('inspire_theme', models.ManyToManyField(blank=True, related_name='source_inspire_theme', to='inspire.InspireTheme')),
                ('internal_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_contact', to='layers.Contact', verbose_name='Internal Contact')),
                ('internal_responsible_city_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_department', to='layers.Contact')),
            ],
            bases=('layers.layer',),
        ),
        migrations.AddField(
            model_name='inspiremap',
            name='inspire_theme',
            field=models.ManyToManyField(blank=True, related_name='inspire_theme_map', to='inspire.InspireTheme'),
        ),
        migrations.AddField(
            model_name='inspiredataset',
            name='inspire_theme',
            field=models.ManyToManyField(blank=True, related_name='inspire_theme', to='inspire.InspireTheme'),
        ),
    ]
