# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiretheme',
            name='topicCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topicCategory', to='layers.ISOcodelist'),
        ),
        migrations.AlterField(
            model_name='sourcelayer',
            name='internal_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_contact', to='layers.Contact', verbose_name='Internal Contact'),
        ),
        migrations.AlterField(
            model_name='sourcelayer',
            name='internal_responsible_city_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_department', to='layers.Contact'),
        ),
    ]
