# Generated by Django 4.0.2 on 2023-10-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0011_auto_20211023_1604'),
        ('inspire', '0002_auto_20211024_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiretheme',
            name='topicCategory',
            field=models.ForeignKey(blank=True, limit_choices_to={'code_list': 'MD_TopicCategoryCode'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topicCategory', to='layers.isocodelist'),
        ),
        migrations.AlterField(
            model_name='sourcelayer',
            name='internal_responsible_city_department',
            field=models.ForeignKey(limit_choices_to=models.Q(('organisation__startswith', 'Stadt Hameln')), on_delete=django.db.models.deletion.PROTECT, related_name='city_department', to='layers.contact'),
        ),
    ]
