# Generated by Django 4.2.5 on 2024-08-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0003_alter_inspiretheme_topiccategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspireHDV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=400, verbose_name='URI')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (en)')),
                ('name_de', models.CharField(max_length=200, verbose_name='Name (de)')),
            ],
        ),
        migrations.AddField(
            model_name='sourcelayer',
            name='inspire_hdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspire_hdv', to='inspire.inspirehdv'),
        ),
    ]
