# Generated by Django 4.2.5 on 2024-08-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0004_inspirehdv_sourcelayer_inspire_hdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcelayer',
            name='inspire_hdv',
        ),
        migrations.AddField(
            model_name='inspiredataset',
            name='inspire_hdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspire_hdv', to='inspire.inspirehdv'),
        ),
    ]
