# Generated by Django 4.2.5 on 2026-01-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inspire", "0006_inspiremap_inspire_hdv"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InspireHVD",
            new_name="InspireHDV",
        ),
        migrations.RenameField(
            model_name="inspiredataset",
            old_name="inspire_hvd",
            new_name="inspire_hdv",
        ),
        migrations.RenameField(
            model_name="inspiremap",
            old_name="inspire_hvd",
            new_name="inspire_hdv",
        ),
    ]
